env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "tTyvKckPrcvShByiskYbD0BaHZSJ1SRcCILc3qx+CyZx3o5uJHZGlxTVTUTevjLM6C3ZPpD9tRL5QxjnRNYPrm0nF6pEgMnf0AXi5F+/n6kNKqLjm+FyKi8E792x7RhkS1kyONmtzS9mgDWaVK1Tql9SgaLH3qQypyWG7zsdl6C68ReN3PiqtmwrKW0jcCjgWg7VW5pqKt5ljCEbe9EskJvbZJSfXr0+YUDnAjtJCGKHqJI8Hn07rxUD8LXJouQyqJ3xrhZysWVf4QdZprUMbgPQStJJAXBTNF3UcqhGrexUm/lwlHLSYByYb0fhoqhJ4NdzzWPtNpeX90QIf+cBbBVL25094bec2/BlurvqTGbBVn2Al0Nuxee+jJu6K8pYUUelUbU43Iy4ecX1xjOLTo0dknnpzXlzSDl5MS5eDig9F8cK4BLm75yZKT+s6hNR4Y8vdpbdCXCfyDyD8GYRG1xcerfZxIIwxqkFn8otEMiKcEEq/xZmBqmRpmOgFQ0W8wD9teU5+34taTZQEJBZGe96Ae/j0eYzNtqQY4LVyIaim3vstwV23MORM3SMVeTANws/oPRYKuhSsXRXl35V4kqRlZYM30UaZwvLKpb80NlyUmaZcaiAQGykGR7F2SDOcYLom3mZwhPPjATFMfY0uv4yaDBZj2I6iH1EHjW63zs="

os:
  - linux
  - osx

sudo: true
language:
  - c
before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=RELEASE ..
script:
  - make all
addons:
  coverity_scan:
    project:
      name: "orpiske/gru"
      description: "Generic Reusable Utilities"
    notification_email: angusyoung@gmail.com
    build_command_prepend: "mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RELEASE .."
    build_command: "make all"
    branch_pattern: coverity_scan
